---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-broker
  namespace: default
spec:
  selector:
    matchLabels:
      role: my-service-broker
  replicas: 1
  template:
    metadata:
      labels:
        role: my-service-broker
    spec:
      containers:
      - name: service-broker
        image: portepa/service-broker
        env:
          - name: BROKER_SERVICE_URL
            value: jdbc:postgresql://35.187.17.121:5432/mydb?user=postgres&password=easypassword&ssl=false
          - name: BROKER_SERVICE_ID
            value: psql-k8s-broker-id
          - name: BROKER_SERVICE_NAME
            value: psql-k8s-broker
          - name: BROKER_SERVICE_ICON
            value: https://s3-eu-west-1.amazonaws.com/public-pporte-bucket/ops-guy.png
          - name: BROKER_SERVICE_TAG
            value: my-tag
          - name: BROKER_CREDENTIALS_PASSWORD
            value: easypassword
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: psql-service-broker
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    role: my-service-broker
